'------------------------------------------------------------------------------
#INCLUDE "Win32API.inc"  ' Win32 API 声明与等式，等
#INCLUDE "CommCtrl.inc"  ' 通用控件声明与等式，等
#INCLUDE "InitCtrl.inc"  ' 用于初始化通用控件
#INCLUDE "ComDlg32.inc"  ' 通用对话框声明与等式，等
#INCLUDE "MDI32.inc"     ' 一些MDI相关调用的封装
#INCLUDE "TabCtrl.inc"
'#INCLUDE "ComboBoxCtrl.inc"
#INCLUDE "ComboCtrl.inc"
#INCLUDE "ListBoxCtrl.inc"
#INCLUDE "ListViewCtrl.inc"
#INCLUDE "TreeViewCtrl.inc"
#INCLUDE "RebarCtrl.inc"
#INCLUDE "sqlite.inc"
#INCLUDE "trm.inc"
#INCLUDE "Ddoc_p32.inc"
#INCLUDE "sci.inc"
#INCLUDE "sci_print.inc"
#INCLUDE "types.inc"

#INCLUDE "splash.bas"
#INCLUDE "option.bas"
#INCLUDE "edit.bas"
#INCLUDE "toolbar.bas"
#INCLUDE "dock.INC"
#INCLUDE "property.INC"
#INCLUDE "toolwin.INC"
#INCLUDE "project.INC"
#INCLUDE "compilers.INC"  '编译结果展示窗口
#INCLUDE "findrs.INC"
#INCLUDE "util.bas"
#INCLUDE "compileform.inc"    '表单form窗口转换成代码
#INCLUDE "form.inc"
#INCLUDE "compilecode.inc"    '编译代码
#INCLUDE "dlg.inc"
